### ISSUE TITLE
Unable to Install (Windows 8 R 3.1.0)

### ISSUE THREAD

**Issue by mauricioromero86** [overcoil/X4R#10]
I try to use the following commands
install.packages("devtools")
library(devtools)
install_github("overcoil/X4R")

But get the following error message

Downloading github repo overcoil/X4R@master
Installing X4R
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\Mauricio\AppData\Local\Temp\RtmpQ9igy1\devtools2fc03f84a1a\overcoil-X4R-75de0a6"  \
  --library="C:/Users/Mauricio/Documents/R/win-library/3.1" --install-tests 
- installing _source_ package 'X4R' ...
  *\* libs

**\* arch - i386
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I.   -I"C:/Users/Mauricio/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c X4R.cpp -o X4R.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I.   -I"C:/Users/Mauricio/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c soapC.cpp -o soapC.o
soapC.cpp:5631:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
soapC.cpp:5632:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
soapC.cpp:5754:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I.   -I"C:/Users/Mauricio/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c soapXmlaWebServiceSoapProxy.cpp -o soapXmlaWebServiceSoapProxy.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I.   -I"C:/Users/Mauricio/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c stdsoap2.cpp -o stdsoap2.o
stdsoap2.cpp:75:0: warning: ignoring #pragma comment  [-Wunknown-pragmas]
stdsoap2.cpp:77:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
stdsoap2.cpp: In function 'const char\* soap_strerror(soap*)':
stdsoap2.cpp:16229:11: warning: variable 'len' set but not used [-Wunused-but-set-variable]
g++ -m32 -shared -s -static-libgcc -o X4R.dll tmp.def X4R.o soapC.o soapXmlaWebServiceSoapProxy.o stdsoap2.o -LC:/PROGRA~1/R/R-31~1.2/library/Rcpp/libs/i386 -LC:/PROGRA~1/R/R-31~1.2/library/Rcpp/libs/x64 -lRcpp -lws2_32 -Ld:/RCompile/CRANpkg/extralibs64/local/lib/i386 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/PROGRA~1/R/R-31~1.2/bin/i386 -lR
c:/rtools/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lRcpp
collect2: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'X4R'
- removing 'C:/Users/Mauricio/Documents/R/win-library/3.1/X4R'
- restoring previous 'C:/Users/Mauricio/Documents/R/win-library/3.1/X4R'
  Error: Command failed (1)

I have never installed a package from git_hub before using devtools... so I'm not sure if I miss a step or something.

Thanks!

**Comment by tu-artem** [comment]
@mauricioromero86 Hello!

I have exactly the same problem, but I am really new to R and RStudio.
Can you please tell me how to change the path to Rcpp to solve this problem?

Thanks a lot!

**Comment by mauricioromero86** [comment]
Hi,

Well i used the following code

install.packages("Rcpp",.libPaths()[2])
install.packages("devtools")
library(devtools)
install_github("overcoil/X4R")

The first bit is telling R to use the appropiuate path to install Rcpp.

Does that make sense? I hope this is useful

Best,

M

**Comment by tu-artem** [comment]
Hello!
Thank you for your answer!

Actually I have just copy the Rcpp folder from one directory to the other and that made sence.
But your way is much easier and clear)

thanx
